# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookWorm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookWorm
  pod 'Parse'
  pod 'Parse/UI'
  pod 'FBSDKLoginKit'
  pod 'AFNetworking'
  pod 'ParseLiveQuery'
  pod 'DZNEmptyDataSet'

  target 'BookWormTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookWormUITests' do
    # Pods for testing
  end

end
